export const folderStructure = {
  MyProject: [
    "00.Workspaces",
    "01.Finance",
    "02.Parser",
    "03.Connector",
    "04.Conditional Rule",
    "05.Derivative Rule",
    "06.Cube View Extender",
    "07.Dashboard Data Set",
    "08.Dashboard Extender",
    "09.Dashboard XFBR String",
    "10.Extensibility Rule",
    "11.Spreadsheet",
    "12.Smart Integration Function",
    "98.System",
    "99.Unknown",
  ],
};

export const ruleTypeToFolderName = {
  Unknown: "12.Unknown",
  Finance: "01.Finance",
  Parser: "02.Parser",
  Connector: "03.Connector",
  ConditionalRule: "04.Conditional Rule",
  DerivativeRule: "05.Derivative Rule",
  CubeViewExtender: "06.Cube View Extender",
  DashboardDataSet: "07.Dashboard Data Set",
  DashboardExtender: "08.Dashboard Extender",
  DashboardStringFunction: "09.Dashboard XFBR String",
  Spreadsheet: "11.Spreadsheet",
  Extender: "10.Extensibility Rule",
  SystemExtender: "98.System",
  WcfEventHandler: "10.Extensibility Rule",
  TransformationEventHandler: "10.Extensibility Rule",
  JournalsEventHandler: "10.Extensibility Rule",
  FormsEventHandler: "10.Extensibility Rule",
  DataQualityEventHandler: "10.Extensibility Rule",
  DataManagementEventHandler: "10.Extensibility Rule",
  WorkflowEventHandler: "10.Extensibility Rule",
  SaveDataEventHandler: "10.Extensibility Rule",
  SmartIntegrationFunction: "12.Smart Integration Function",
};
